import { User } from '../modals/User';

export var userList: User[] = [
    {"id": 1,"enable":"no", "vname": "Roy@gmail.com","fname": "Roy", 
    "lname": "Oake", "permission": "Admin", "skills":"skills","chatlimit":5,
    "emaillimit":10,"IP":"10.0.0.85","online":"yes"},
    {"id": 2,"enable":"yes", "vname": "Adriana@gmail.com","fname": "Adriana", 
    "lname": "Jones", "permission": "Admin", "skills":"skills","chatlimit":4,
    "emaillimit":1,"IP":"10.15.0.85","online":"no"},
    {"id": 3,"enable":"no", "vname": "Adriana@gmail.com","fname": "Kapil", 
    "lname": "Jones", "permission": "Admin", "skills":"skills","chatlimit":5,
    "emaillimit":10,"IP":"10.0.0.85","online":"yes"},
    {"id": 4,"enable":"yes", "vname": "Indiana@gmail.com","fname": "Indiana", 
    "lname": "Jones", "permission": "Admin", "skills":"skills","chatlimit":6,
    "emaillimit":5,"IP":"10.0.0.85","online":"yes"},
    {"id": 5,"enable":"no", "vname": "Adriana@gmail.com","fname": "Adriana", 
    "lname": "Jones", "permission": "Admin", "skills":"skills","chatlimit":10,
    "emaillimit":10,"IP":"10.0.0.81","online":"no"},
    {"id": 6,"enable":"yes", "vname": "Adriana@gmail.com","fname": "Adriana", 
    "lname": "Jones", "permission": "Admin", "skills":"skills","chatlimit":5,
    "emaillimit":4,"IP":"10.0.0.85","online":"yes"},
    {"id": 7,"enable":"no", "vname": "Adriana@gmail.com","fname": "Adriana", 
    "lname": "Jones", "permission": "Admin", "skills":"skills","chatlimit":5,
    "emaillimit":10,"IP":"10.0.0.85","online":"yes"},
    {"id": 8,"enable":"yes", "vname": "Adriana@gmail.com","fname": "Adriana", 
    "lname": "Jones", "permission": "Admin", "skills":"skills","chatlimit":5,
    "emaillimit":10,"IP":"10.0.20.85","online":"no"},
    {"id": 9,"enable":"yes", "vname": "Adriana@gmail.com","fname": "Kapil", 
    "lname": "Jones", "permission": "Admin", "skills":"skills","chatlimit":5,
    "emaillimit":10,"IP":"10.0.0.85","online":"yes"},
    {"id": 10,"enable":"yes", "vname": "Adriana@gmail.com","fname": "Adriana", 
    "lname": "Jones", "permission": "Admin", "skills":"skills","chatlimit":5,
    "emaillimit":10,"IP":"10.0.0.85","online":"yes"},
    {"id": 11,"enable":"yes", "vname": "Adriana@gmail.com","fname": "Adriana", 
    "lname": "Jones", "permission": "Admin", "skills":"skills","chatlimit":5,
    "emaillimit":10,"IP":"10.0.0.85","online":"yes"},
    {"id": 1,"enable":"yes", "vname": "Adriana@gmail.com","fname": "Adriana", 
    "lname": "Jones", "permission": "Admin", "skills":"skills","chatlimit":5,
    "emaillimit":10,"IP":"10.0.0.85","online":"yes"},
    {"id": 1,"enable":"yes", "vname": "Adriana@gmail.com","fname": "Adriana", 
    "lname": "Jones", "permission": "Admin", "skills":"skills","chatlimit":5,
    "emaillimit":10,"IP":"10.0.0.85","online":"yes"},
    {"id": 1,"enable":"yes", "vname": "Adriana@gmail.com","fname": "Adriana", 
    "lname": "Jones", "permission": "Admin", "skills":"skills","chatlimit":5,
    "emaillimit":10,"IP":"10.0.0.85","online":"yes"},
    {"id": 1,"enable":"yes", "vname": "Adriana@gmail.com","fname": "Adriana", 
    "lname": "Jones", "permission": "Admin", "skills":"skills","chatlimit":5,
    "emaillimit":10,"IP":"10.0.0.85","online":"yes"},
    {"id": 1,"enable":"yes", "vname": "Adriana@gmail.com","fname": "Adriana", 
    "lname": "Jones", "permission": "Admin", "skills":"skills","chatlimit":5,
    "emaillimit":10,"IP":"10.0.0.85","online":"yes"},
    {"id": 1,"enable":"yes", "vname": "Adriana@gmail.com","fname": "Adriana", 
    "lname": "Jones", "permission": "Admin", "skills":"skills","chatlimit":5,
    "emaillimit":10,"IP":"10.0.0.85","online":"yes"},
    {"id": 1,"enable":"yes", "vname": "Adriana@gmail.com","fname": "Adriana", 
    "lname": "Jones", "permission": "Admin", "skills":"skills","chatlimit":5,
    "emaillimit":10,"IP":"10.0.0.85","online":"yes"},
    {"id": 1,"enable":"yes", "vname": "Adriana@gmail.com","fname": "Adriana", 
    "lname": "Jones", "permission": "Admin", "skills":"skills","chatlimit":5,
    "emaillimit":10,"IP":"10.0.0.85","online":"yes"},
    {"id": 1,"enable":"yes", "vname": "Adriana@gmail.com","fname": "Adriana", 
    "lname": "Jones", "permission": "Admin", "skills":"skills","chatlimit":5,
    "emaillimit":10,"IP":"10.0.0.85","online":"yes"},
    ]


